//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.30 at 06:38:40 PM PDT 
//


package com.hingeto.api;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for BillingData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BillingData">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BuyerEmailAddress" type="{https://www.hingeto.com/xml/V0.1}BuyerEmailAddress" minOccurs="0"/>
 *         &lt;element name="BuyerName" type="{https://www.hingeto.com/xml/V0.1}String255" minOccurs="0"/>
 *         &lt;element name="BuyerPhoneNumber" type="{https://www.hingeto.com/xml/V0.1}String255" minOccurs="0"/>
 *         &lt;element name="PaymentInfo" type="{https://www.hingeto.com/xml/V0.1}String255" minOccurs="0"/>
 *         &lt;element name="BillingAddress" type="{https://www.hingeto.com/xml/V0.1}Address" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BillingData", propOrder = {
    "buyerEmailAddress",
    "buyerName",
    "buyerPhoneNumber",
    "paymentInfo",
    "billingAddress"
})
public class BillingData {

    @XmlElement(name = "BuyerEmailAddress")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String buyerEmailAddress;
    @XmlElement(name = "BuyerName")
    protected String buyerName;
    @XmlElement(name = "BuyerPhoneNumber")
    protected String buyerPhoneNumber;
    @XmlElement(name = "PaymentInfo")
    protected String paymentInfo;
    @XmlElement(name = "BillingAddress")
    protected Address billingAddress;

    /**
     * Gets the value of the buyerEmailAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBuyerEmailAddress() {
        return buyerEmailAddress;
    }

    /**
     * Sets the value of the buyerEmailAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBuyerEmailAddress(String value) {
        this.buyerEmailAddress = value;
    }

    /**
     * Gets the value of the buyerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBuyerName() {
        return buyerName;
    }

    /**
     * Sets the value of the buyerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBuyerName(String value) {
        this.buyerName = value;
    }

    /**
     * Gets the value of the buyerPhoneNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBuyerPhoneNumber() {
        return buyerPhoneNumber;
    }

    /**
     * Sets the value of the buyerPhoneNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBuyerPhoneNumber(String value) {
        this.buyerPhoneNumber = value;
    }

    /**
     * Gets the value of the paymentInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentInfo() {
        return paymentInfo;
    }

    /**
     * Sets the value of the paymentInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentInfo(String value) {
        this.paymentInfo = value;
    }

    /**
     * Gets the value of the billingAddress property.
     * 
     * @return
     *     possible object is
     *     {@link Address }
     *     
     */
    public Address getBillingAddress() {
        return billingAddress;
    }

    /**
     * Sets the value of the billingAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link Address }
     *     
     */
    public void setBillingAddress(Address value) {
        this.billingAddress = value;
    }

}
