//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.30 at 06:38:40 PM PDT 
//


package com.hingeto.api;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CancellationItem complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CancellationItem">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="OrderItemCode" type="{https://www.hingeto.com/xml/V0.1}OrderItemCode"/>
 *         &lt;element name="StoreFrontLineItemID" type="{https://www.hingeto.com/xml/V0.1}StoreFrontLineItem"/>
 *         &lt;element name="ListingID" type="{https://www.hingeto.com/xml/V0.1}ListingIDType"/>
 *         &lt;element name="CancelReason" type="{https://www.hingeto.com/xml/V0.1}String255" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CancellationItem", propOrder = {
    "orderItemCode",
    "storeFrontLineItemID",
    "listingID",
    "cancelReason"
})
public class CancellationItem {

    @XmlElement(name = "OrderItemCode", required = true)
    protected String orderItemCode;
    @XmlElement(name = "StoreFrontLineItemID", required = true)
    protected String storeFrontLineItemID;
    @XmlElement(name = "ListingID", required = true)
    protected ListingIDType listingID;
    @XmlElement(name = "CancelReason")
    protected String cancelReason;

    /**
     * Gets the value of the orderItemCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderItemCode() {
        return orderItemCode;
    }

    /**
     * Sets the value of the orderItemCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderItemCode(String value) {
        this.orderItemCode = value;
    }

    /**
     * Gets the value of the storeFrontLineItemID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStoreFrontLineItemID() {
        return storeFrontLineItemID;
    }

    /**
     * Sets the value of the storeFrontLineItemID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStoreFrontLineItemID(String value) {
        this.storeFrontLineItemID = value;
    }

    /**
     * Gets the value of the listingID property.
     * 
     * @return
     *     possible object is
     *     {@link ListingIDType }
     *     
     */
    public ListingIDType getListingID() {
        return listingID;
    }

    /**
     * Sets the value of the listingID property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListingIDType }
     *     
     */
    public void setListingID(ListingIDType value) {
        this.listingID = value;
    }

    /**
     * Gets the value of the cancelReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCancelReason() {
        return cancelReason;
    }

    /**
     * Sets the value of the cancelReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCancelReason(String value) {
        this.cancelReason = value;
    }

}
