//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.30 at 06:38:40 PM PDT 
//


package com.hingeto.api;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CategoryAssignmentMessage complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CategoryAssignmentMessage">
 *   &lt;complexContent>
 *     &lt;extension base="{https://www.hingeto.com/xml/V0.1}ProductMessage">
 *       &lt;sequence>
 *         &lt;element name="CategoryAssignmentData" type="{https://www.hingeto.com/xml/V0.1}CategoryAssignmentData"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CategoryAssignmentMessage", propOrder = {
    "categoryAssignmentData"
})
public class CategoryAssignmentMessage
    extends ProductMessage
{

    @XmlElement(name = "CategoryAssignmentData", required = true)
    protected CategoryAssignmentData categoryAssignmentData;

    /**
     * Gets the value of the categoryAssignmentData property.
     * 
     * @return
     *     possible object is
     *     {@link CategoryAssignmentData }
     *     
     */
    public CategoryAssignmentData getCategoryAssignmentData() {
        return categoryAssignmentData;
    }

    /**
     * Sets the value of the categoryAssignmentData property.
     * 
     * @param value
     *     allowed object is
     *     {@link CategoryAssignmentData }
     *     
     */
    public void setCategoryAssignmentData(CategoryAssignmentData value) {
        this.categoryAssignmentData = value;
    }

}
