//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.30 at 06:38:40 PM PDT 
//


package com.hingeto.api;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Condition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Condition">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="ConditionValue" type="{https://www.hingeto.com/xml/V0.1}ConditionDictionary"/>
 *         &lt;element name="ConditionFreeText" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Condition", propOrder = {
    "conditionValue",
    "conditionFreeText"
})
public class Condition {

    @XmlElement(name = "ConditionValue")
    protected ConditionDictionary conditionValue;
    @XmlElement(name = "ConditionFreeText")
    protected String conditionFreeText;

    /**
     * Gets the value of the conditionValue property.
     * 
     * @return
     *     possible object is
     *     {@link ConditionDictionary }
     *     
     */
    public ConditionDictionary getConditionValue() {
        return conditionValue;
    }

    /**
     * Sets the value of the conditionValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConditionDictionary }
     *     
     */
    public void setConditionValue(ConditionDictionary value) {
        this.conditionValue = value;
    }

    /**
     * Gets the value of the conditionFreeText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConditionFreeText() {
        return conditionFreeText;
    }

    /**
     * Sets the value of the conditionFreeText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConditionFreeText(String value) {
        this.conditionFreeText = value;
    }

}
