//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.30 at 06:38:40 PM PDT 
//


package com.hingeto.api;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ConditionDictionary.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ConditionDictionary">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="New"/>
 *     &lt;enumeration value="UsedLikeNew"/>
 *     &lt;enumeration value="UsedVeryGood"/>
 *     &lt;enumeration value="UsedGood"/>
 *     &lt;enumeration value="UsedAcceptable"/>
 *     &lt;enumeration value="Refurbished"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ConditionDictionary")
@XmlEnum
public enum ConditionDictionary {

    @XmlEnumValue("New")
    NEW("New"),
    @XmlEnumValue("UsedLikeNew")
    USED_LIKE_NEW("UsedLikeNew"),
    @XmlEnumValue("UsedVeryGood")
    USED_VERY_GOOD("UsedVeryGood"),
    @XmlEnumValue("UsedGood")
    USED_GOOD("UsedGood"),
    @XmlEnumValue("UsedAcceptable")
    USED_ACCEPTABLE("UsedAcceptable"),
    @XmlEnumValue("Refurbished")
    REFURBISHED("Refurbished");
    private final String value;

    ConditionDictionary(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ConditionDictionary fromValue(String v) {
        for (ConditionDictionary c: ConditionDictionary.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
