//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.30 at 06:38:40 PM PDT 
//


package com.hingeto.api;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Dimensions complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Dimensions">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ItemDimensionsLength" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="ItemDimensionsWidth" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="ItemDimensionsHeight" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="DimensionsUnit" type="{https://www.hingeto.com/xml/V0.1}DimensionsUnit"/>
 *         &lt;element name="ShippingWeight" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="WeightUnit" type="{https://www.hingeto.com/xml/V0.1}WeightUnit"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Dimensions", propOrder = {
    "itemDimensionsLength",
    "itemDimensionsWidth",
    "itemDimensionsHeight",
    "dimensionsUnit",
    "shippingWeight",
    "weightUnit"
})
public class Dimensions {

    @XmlElement(name = "ItemDimensionsLength")
    protected BigDecimal itemDimensionsLength;
    @XmlElement(name = "ItemDimensionsWidth")
    protected BigDecimal itemDimensionsWidth;
    @XmlElement(name = "ItemDimensionsHeight")
    protected BigDecimal itemDimensionsHeight;
    @XmlElement(name = "DimensionsUnit", required = true)
    protected DimensionsUnit dimensionsUnit;
    @XmlElement(name = "ShippingWeight")
    protected BigDecimal shippingWeight;
    @XmlElement(name = "WeightUnit", required = true)
    protected WeightUnit weightUnit;

    /**
     * Gets the value of the itemDimensionsLength property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getItemDimensionsLength() {
        return itemDimensionsLength;
    }

    /**
     * Sets the value of the itemDimensionsLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setItemDimensionsLength(BigDecimal value) {
        this.itemDimensionsLength = value;
    }

    /**
     * Gets the value of the itemDimensionsWidth property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getItemDimensionsWidth() {
        return itemDimensionsWidth;
    }

    /**
     * Sets the value of the itemDimensionsWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setItemDimensionsWidth(BigDecimal value) {
        this.itemDimensionsWidth = value;
    }

    /**
     * Gets the value of the itemDimensionsHeight property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getItemDimensionsHeight() {
        return itemDimensionsHeight;
    }

    /**
     * Sets the value of the itemDimensionsHeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setItemDimensionsHeight(BigDecimal value) {
        this.itemDimensionsHeight = value;
    }

    /**
     * Gets the value of the dimensionsUnit property.
     * 
     * @return
     *     possible object is
     *     {@link DimensionsUnit }
     *     
     */
    public DimensionsUnit getDimensionsUnit() {
        return dimensionsUnit;
    }

    /**
     * Sets the value of the dimensionsUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link DimensionsUnit }
     *     
     */
    public void setDimensionsUnit(DimensionsUnit value) {
        this.dimensionsUnit = value;
    }

    /**
     * Gets the value of the shippingWeight property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getShippingWeight() {
        return shippingWeight;
    }

    /**
     * Sets the value of the shippingWeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setShippingWeight(BigDecimal value) {
        this.shippingWeight = value;
    }

    /**
     * Gets the value of the weightUnit property.
     * 
     * @return
     *     possible object is
     *     {@link WeightUnit }
     *     
     */
    public WeightUnit getWeightUnit() {
        return weightUnit;
    }

    /**
     * Sets the value of the weightUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link WeightUnit }
     *     
     */
    public void setWeightUnit(WeightUnit value) {
        this.weightUnit = value;
    }

}
