//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.30 at 06:38:40 PM PDT 
//


package com.hingeto.api;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Header" type="{https://www.hingeto.com/xml/V0.1}Header"/>
 *         &lt;choice>
 *           &lt;element name="Products" type="{https://www.hingeto.com/xml/V0.1}ProductContentList"/>
 *           &lt;element name="ImageURLs" type="{https://www.hingeto.com/xml/V0.1}ImageURLList"/>
 *           &lt;element name="CategoryAssignments" type="{https://www.hingeto.com/xml/V0.1}CategoryAssignmentList"/>
 *           &lt;element name="Listings" type="{https://www.hingeto.com/xml/V0.1}ListingList"/>
 *           &lt;element name="FullProducts" type="{https://www.hingeto.com/xml/V0.1}FullProductList"/>
 *           &lt;element name="Orders" type="{https://www.hingeto.com/xml/V0.1}OrderList"/>
 *           &lt;element name="RMAs" type="{https://www.hingeto.com/xml/V0.1}RMAList"/>
 *           &lt;element name="RefundRequests" type="{https://www.hingeto.com/xml/V0.1}RefundRequestList"/>
 *           &lt;element name="Refunds" type="{https://www.hingeto.com/xml/V0.1}RefundList"/>
 *           &lt;element name="Returns" type="{https://www.hingeto.com/xml/V0.1}ReturnList"/>
 *           &lt;element name="OrderStatus" type="{https://www.hingeto.com/xml/V0.1}OrderStatusList"/>
 *           &lt;element name="StorefrontTree" type="{https://www.hingeto.com/xml/V0.1}StorefrontTree"/>
 *           &lt;element name="ShippingCalculations" type="{https://www.hingeto.com/xml/V0.1}ShippingCalculationList"/>
 *           &lt;element name="ProcessingResponse" type="{https://www.hingeto.com/xml/V0.1}ProcessingResponse"/>
 *           &lt;element name="NewProductAuthorization" type="{https://www.hingeto.com/xml/V0.1}ProductContentList"/>
 *           &lt;element name="NewProductAuthorizationResponse" type="{https://www.hingeto.com/xml/V0.1}NewProductAuthorizationResponse"/>
 *           &lt;element name="ProductResponse" type="{https://www.hingeto.com/xml/V0.1}ProductResponse"/>
 *           &lt;element name="ListingResponse" type="{https://www.hingeto.com/xml/V0.1}ListingResponse"/>
 *           &lt;element name="Suppliers" type="{https://www.hingeto.com/xml/V0.1}SupplierList"/>
 *           &lt;element name="SupplierCommissions" type="{https://www.hingeto.com/xml/V0.1}SupplierCommissionList"/>
 *           &lt;element name="validationResults" type="{https://www.hingeto.com/xml/V0.1}validationResults"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "header",
    "products",
    "imageURLs",
    "categoryAssignments",
    "listings",
    "fullProducts",
    "orders",
    "rmAs",
    "refundRequests",
    "refunds",
    "returns",
    "orderStatus",
    "storefrontTree",
    "shippingCalculations",
    "processingResponse",
    "newProductAuthorization",
    "newProductAuthorizationResponse",
    "productResponse",
    "listingResponse",
    "suppliers",
    "supplierCommissions",
    "validationResults"
})
@XmlRootElement(name = "feed")
public class Feed {

    @XmlElement(name = "Header", required = true)
    protected Header header;
    @XmlElement(name = "Products")
    protected ProductContentList products;
    @XmlElement(name = "ImageURLs")
    protected ImageURLList imageURLs;
    @XmlElement(name = "CategoryAssignments")
    protected CategoryAssignmentList categoryAssignments;
    @XmlElement(name = "Listings")
    protected ListingList listings;
    @XmlElement(name = "FullProducts")
    protected FullProductList fullProducts;
    @XmlElement(name = "Orders")
    protected OrderList orders;
    @XmlElement(name = "RMAs")
    protected RMAList rmAs;
    @XmlElement(name = "RefundRequests")
    protected RefundRequestList refundRequests;
    @XmlElement(name = "Refunds")
    protected RefundList refunds;
    @XmlElement(name = "Returns")
    protected ReturnList returns;
    @XmlElement(name = "OrderStatus")
    protected OrderStatusList orderStatus;
    @XmlElement(name = "StorefrontTree")
    protected StorefrontTree storefrontTree;
    @XmlElement(name = "ShippingCalculations")
    protected ShippingCalculationList shippingCalculations;
    @XmlElement(name = "ProcessingResponse")
    protected ProcessingResponse processingResponse;
    @XmlElement(name = "NewProductAuthorization")
    protected ProductContentList newProductAuthorization;
    @XmlElement(name = "NewProductAuthorizationResponse")
    protected NewProductAuthorizationResponse newProductAuthorizationResponse;
    @XmlElement(name = "ProductResponse")
    protected ProductResponse productResponse;
    @XmlElement(name = "ListingResponse")
    protected ListingResponse listingResponse;
    @XmlElement(name = "Suppliers")
    protected SupplierList suppliers;
    @XmlElement(name = "SupplierCommissions")
    protected SupplierCommissionList supplierCommissions;
    protected ValidationResults validationResults;

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link Header }
     *     
     */
    public Header getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link Header }
     *     
     */
    public void setHeader(Header value) {
        this.header = value;
    }

    /**
     * Gets the value of the products property.
     * 
     * @return
     *     possible object is
     *     {@link ProductContentList }
     *     
     */
    public ProductContentList getProducts() {
        return products;
    }

    /**
     * Sets the value of the products property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductContentList }
     *     
     */
    public void setProducts(ProductContentList value) {
        this.products = value;
    }

    /**
     * Gets the value of the imageURLs property.
     * 
     * @return
     *     possible object is
     *     {@link ImageURLList }
     *     
     */
    public ImageURLList getImageURLs() {
        return imageURLs;
    }

    /**
     * Sets the value of the imageURLs property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImageURLList }
     *     
     */
    public void setImageURLs(ImageURLList value) {
        this.imageURLs = value;
    }

    /**
     * Gets the value of the categoryAssignments property.
     * 
     * @return
     *     possible object is
     *     {@link CategoryAssignmentList }
     *     
     */
    public CategoryAssignmentList getCategoryAssignments() {
        return categoryAssignments;
    }

    /**
     * Sets the value of the categoryAssignments property.
     * 
     * @param value
     *     allowed object is
     *     {@link CategoryAssignmentList }
     *     
     */
    public void setCategoryAssignments(CategoryAssignmentList value) {
        this.categoryAssignments = value;
    }

    /**
     * Gets the value of the listings property.
     * 
     * @return
     *     possible object is
     *     {@link ListingList }
     *     
     */
    public ListingList getListings() {
        return listings;
    }

    /**
     * Sets the value of the listings property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListingList }
     *     
     */
    public void setListings(ListingList value) {
        this.listings = value;
    }

    /**
     * Gets the value of the fullProducts property.
     * 
     * @return
     *     possible object is
     *     {@link FullProductList }
     *     
     */
    public FullProductList getFullProducts() {
        return fullProducts;
    }

    /**
     * Sets the value of the fullProducts property.
     * 
     * @param value
     *     allowed object is
     *     {@link FullProductList }
     *     
     */
    public void setFullProducts(FullProductList value) {
        this.fullProducts = value;
    }

    /**
     * Gets the value of the orders property.
     * 
     * @return
     *     possible object is
     *     {@link OrderList }
     *     
     */
    public OrderList getOrders() {
        return orders;
    }

    /**
     * Sets the value of the orders property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderList }
     *     
     */
    public void setOrders(OrderList value) {
        this.orders = value;
    }

    /**
     * Gets the value of the rmAs property.
     * 
     * @return
     *     possible object is
     *     {@link RMAList }
     *     
     */
    public RMAList getRMAs() {
        return rmAs;
    }

    /**
     * Sets the value of the rmAs property.
     * 
     * @param value
     *     allowed object is
     *     {@link RMAList }
     *     
     */
    public void setRMAs(RMAList value) {
        this.rmAs = value;
    }

    /**
     * Gets the value of the refundRequests property.
     * 
     * @return
     *     possible object is
     *     {@link RefundRequestList }
     *     
     */
    public RefundRequestList getRefundRequests() {
        return refundRequests;
    }

    /**
     * Sets the value of the refundRequests property.
     * 
     * @param value
     *     allowed object is
     *     {@link RefundRequestList }
     *     
     */
    public void setRefundRequests(RefundRequestList value) {
        this.refundRequests = value;
    }

    /**
     * Gets the value of the refunds property.
     * 
     * @return
     *     possible object is
     *     {@link RefundList }
     *     
     */
    public RefundList getRefunds() {
        return refunds;
    }

    /**
     * Sets the value of the refunds property.
     * 
     * @param value
     *     allowed object is
     *     {@link RefundList }
     *     
     */
    public void setRefunds(RefundList value) {
        this.refunds = value;
    }

    /**
     * Gets the value of the returns property.
     * 
     * @return
     *     possible object is
     *     {@link ReturnList }
     *     
     */
    public ReturnList getReturns() {
        return returns;
    }

    /**
     * Sets the value of the returns property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReturnList }
     *     
     */
    public void setReturns(ReturnList value) {
        this.returns = value;
    }

    /**
     * Gets the value of the orderStatus property.
     * 
     * @return
     *     possible object is
     *     {@link OrderStatusList }
     *     
     */
    public OrderStatusList getOrderStatus() {
        return orderStatus;
    }

    /**
     * Sets the value of the orderStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderStatusList }
     *     
     */
    public void setOrderStatus(OrderStatusList value) {
        this.orderStatus = value;
    }

    /**
     * Gets the value of the storefrontTree property.
     * 
     * @return
     *     possible object is
     *     {@link StorefrontTree }
     *     
     */
    public StorefrontTree getStorefrontTree() {
        return storefrontTree;
    }

    /**
     * Sets the value of the storefrontTree property.
     * 
     * @param value
     *     allowed object is
     *     {@link StorefrontTree }
     *     
     */
    public void setStorefrontTree(StorefrontTree value) {
        this.storefrontTree = value;
    }

    /**
     * Gets the value of the shippingCalculations property.
     * 
     * @return
     *     possible object is
     *     {@link ShippingCalculationList }
     *     
     */
    public ShippingCalculationList getShippingCalculations() {
        return shippingCalculations;
    }

    /**
     * Sets the value of the shippingCalculations property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShippingCalculationList }
     *     
     */
    public void setShippingCalculations(ShippingCalculationList value) {
        this.shippingCalculations = value;
    }

    /**
     * Gets the value of the processingResponse property.
     * 
     * @return
     *     possible object is
     *     {@link ProcessingResponse }
     *     
     */
    public ProcessingResponse getProcessingResponse() {
        return processingResponse;
    }

    /**
     * Sets the value of the processingResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProcessingResponse }
     *     
     */
    public void setProcessingResponse(ProcessingResponse value) {
        this.processingResponse = value;
    }

    /**
     * Gets the value of the newProductAuthorization property.
     * 
     * @return
     *     possible object is
     *     {@link ProductContentList }
     *     
     */
    public ProductContentList getNewProductAuthorization() {
        return newProductAuthorization;
    }

    /**
     * Sets the value of the newProductAuthorization property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductContentList }
     *     
     */
    public void setNewProductAuthorization(ProductContentList value) {
        this.newProductAuthorization = value;
    }

    /**
     * Gets the value of the newProductAuthorizationResponse property.
     * 
     * @return
     *     possible object is
     *     {@link NewProductAuthorizationResponse }
     *     
     */
    public NewProductAuthorizationResponse getNewProductAuthorizationResponse() {
        return newProductAuthorizationResponse;
    }

    /**
     * Sets the value of the newProductAuthorizationResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link NewProductAuthorizationResponse }
     *     
     */
    public void setNewProductAuthorizationResponse(NewProductAuthorizationResponse value) {
        this.newProductAuthorizationResponse = value;
    }

    /**
     * Gets the value of the productResponse property.
     * 
     * @return
     *     possible object is
     *     {@link ProductResponse }
     *     
     */
    public ProductResponse getProductResponse() {
        return productResponse;
    }

    /**
     * Sets the value of the productResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductResponse }
     *     
     */
    public void setProductResponse(ProductResponse value) {
        this.productResponse = value;
    }

    /**
     * Gets the value of the listingResponse property.
     * 
     * @return
     *     possible object is
     *     {@link ListingResponse }
     *     
     */
    public ListingResponse getListingResponse() {
        return listingResponse;
    }

    /**
     * Sets the value of the listingResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListingResponse }
     *     
     */
    public void setListingResponse(ListingResponse value) {
        this.listingResponse = value;
    }

    /**
     * Gets the value of the suppliers property.
     * 
     * @return
     *     possible object is
     *     {@link SupplierList }
     *     
     */
    public SupplierList getSuppliers() {
        return suppliers;
    }

    /**
     * Sets the value of the suppliers property.
     * 
     * @param value
     *     allowed object is
     *     {@link SupplierList }
     *     
     */
    public void setSuppliers(SupplierList value) {
        this.suppliers = value;
    }

    /**
     * Gets the value of the supplierCommissions property.
     * 
     * @return
     *     possible object is
     *     {@link SupplierCommissionList }
     *     
     */
    public SupplierCommissionList getSupplierCommissions() {
        return supplierCommissions;
    }

    /**
     * Sets the value of the supplierCommissions property.
     * 
     * @param value
     *     allowed object is
     *     {@link SupplierCommissionList }
     *     
     */
    public void setSupplierCommissions(SupplierCommissionList value) {
        this.supplierCommissions = value;
    }

    /**
     * Gets the value of the validationResults property.
     * 
     * @return
     *     possible object is
     *     {@link ValidationResults }
     *     
     */
    public ValidationResults getValidationResults() {
        return validationResults;
    }

    /**
     * Sets the value of the validationResults property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValidationResults }
     *     
     */
    public void setValidationResults(ValidationResults value) {
        this.validationResults = value;
    }

}
