//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.30 at 06:38:40 PM PDT 
//


package com.hingeto.api;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FulfillmentData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FulfillmentData">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ShippingOption" type="{https://www.hingeto.com/xml/V0.1}String255"/>
 *         &lt;element name="FulfillmentAddress" type="{https://www.hingeto.com/xml/V0.1}Address" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FulfillmentData", propOrder = {
    "shippingOption",
    "fulfillmentAddress"
})
public class FulfillmentData {

    @XmlElement(name = "ShippingOption", required = true)
    protected String shippingOption;
    @XmlElement(name = "FulfillmentAddress")
    protected Address fulfillmentAddress;

    /**
     * Gets the value of the shippingOption property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShippingOption() {
        return shippingOption;
    }

    /**
     * Sets the value of the shippingOption property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShippingOption(String value) {
        this.shippingOption = value;
    }

    /**
     * Gets the value of the fulfillmentAddress property.
     * 
     * @return
     *     possible object is
     *     {@link Address }
     *     
     */
    public Address getFulfillmentAddress() {
        return fulfillmentAddress;
    }

    /**
     * Sets the value of the fulfillmentAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link Address }
     *     
     */
    public void setFulfillmentAddress(Address value) {
        this.fulfillmentAddress = value;
    }

}
