//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.30 at 06:38:40 PM PDT 
//


package com.hingeto.api;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FullProductMessage complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FullProductMessage">
 *   &lt;complexContent>
 *     &lt;extension base="{https://www.hingeto.com/xml/V0.1}ContentMessage">
 *       &lt;sequence>
 *         &lt;element name="PriceData" type="{https://www.hingeto.com/xml/V0.1}PriceData" minOccurs="0"/>
 *         &lt;element name="ShippingData" type="{https://www.hingeto.com/xml/V0.1}ShippingData" minOccurs="0"/>
 *         &lt;element name="InventoryData" type="{https://www.hingeto.com/xml/V0.1}InventoryData" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FullProductMessage", propOrder = {
    "priceData",
    "shippingData",
    "inventoryData"
})
public class FullProductMessage
    extends ContentMessage
{

    @XmlElement(name = "PriceData")
    protected PriceData priceData;
    @XmlElement(name = "ShippingData")
    protected ShippingData shippingData;
    @XmlElement(name = "InventoryData")
    protected InventoryData inventoryData;

    /**
     * Gets the value of the priceData property.
     * 
     * @return
     *     possible object is
     *     {@link PriceData }
     *     
     */
    public PriceData getPriceData() {
        return priceData;
    }

    /**
     * Sets the value of the priceData property.
     * 
     * @param value
     *     allowed object is
     *     {@link PriceData }
     *     
     */
    public void setPriceData(PriceData value) {
        this.priceData = value;
    }

    /**
     * Gets the value of the shippingData property.
     * 
     * @return
     *     possible object is
     *     {@link ShippingData }
     *     
     */
    public ShippingData getShippingData() {
        return shippingData;
    }

    /**
     * Sets the value of the shippingData property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShippingData }
     *     
     */
    public void setShippingData(ShippingData value) {
        this.shippingData = value;
    }

    /**
     * Gets the value of the inventoryData property.
     * 
     * @return
     *     possible object is
     *     {@link InventoryData }
     *     
     */
    public InventoryData getInventoryData() {
        return inventoryData;
    }

    /**
     * Sets the value of the inventoryData property.
     * 
     * @param value
     *     allowed object is
     *     {@link InventoryData }
     *     
     */
    public void setInventoryData(InventoryData value) {
        this.inventoryData = value;
    }

}
