//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.30 at 06:38:40 PM PDT 
//


package com.hingeto.api;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ImageURLMessage complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ImageURLMessage">
 *   &lt;complexContent>
 *     &lt;extension base="{https://www.hingeto.com/xml/V0.1}ProductMessage">
 *       &lt;sequence>
 *         &lt;element name="ImageURLData" type="{https://www.hingeto.com/xml/V0.1}ImageURLData"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ImageURLMessage", propOrder = {
    "imageURLData"
})
public class ImageURLMessage
    extends ProductMessage
{

    @XmlElement(name = "ImageURLData", required = true)
    protected ImageURLData imageURLData;

    /**
     * Gets the value of the imageURLData property.
     * 
     * @return
     *     possible object is
     *     {@link ImageURLData }
     *     
     */
    public ImageURLData getImageURLData() {
        return imageURLData;
    }

    /**
     * Sets the value of the imageURLData property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImageURLData }
     *     
     */
    public void setImageURLData(ImageURLData value) {
        this.imageURLData = value;
    }

}
