//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.30 at 06:38:40 PM PDT 
//


package com.hingeto.api;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ListingSource complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ListingSource">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ListingID" type="{https://www.hingeto.com/xml/V0.1}ListingIDType"/>
 *         &lt;element name="SupplierName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SupplierConditionNote" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CommissionRate" type="{https://www.hingeto.com/xml/V0.1}CommissionRate" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="OwnListing" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ListingSource", propOrder = {
    "listingID",
    "supplierName",
    "supplierConditionNote",
    "commissionRate"
})
public class ListingSource {

    @XmlElement(name = "ListingID", required = true)
    protected ListingIDType listingID;
    @XmlElement(name = "SupplierName", required = true)
    protected String supplierName;
    @XmlElement(name = "SupplierConditionNote")
    protected String supplierConditionNote;
    @XmlElement(name = "CommissionRate")
    protected BigDecimal commissionRate;
    @XmlAttribute(name = "OwnListing")
    protected Boolean ownListing;

    /**
     * Gets the value of the listingID property.
     * 
     * @return
     *     possible object is
     *     {@link ListingIDType }
     *     
     */
    public ListingIDType getListingID() {
        return listingID;
    }

    /**
     * Sets the value of the listingID property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListingIDType }
     *     
     */
    public void setListingID(ListingIDType value) {
        this.listingID = value;
    }

    /**
     * Gets the value of the supplierName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupplierName() {
        return supplierName;
    }

    /**
     * Sets the value of the supplierName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupplierName(String value) {
        this.supplierName = value;
    }

    /**
     * Gets the value of the supplierConditionNote property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupplierConditionNote() {
        return supplierConditionNote;
    }

    /**
     * Sets the value of the supplierConditionNote property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupplierConditionNote(String value) {
        this.supplierConditionNote = value;
    }

    /**
     * Gets the value of the commissionRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCommissionRate() {
        return commissionRate;
    }

    /**
     * Sets the value of the commissionRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCommissionRate(BigDecimal value) {
        this.commissionRate = value;
    }

    /**
     * Gets the value of the ownListing property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isOwnListing() {
        if (ownListing == null) {
            return false;
        } else {
            return ownListing;
        }
    }

    /**
     * Sets the value of the ownListing property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOwnListing(Boolean value) {
        this.ownListing = value;
    }

}
