//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.30 at 06:38:40 PM PDT 
//


package com.hingeto.api;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ListingMessage complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ListingMessage">
 *   &lt;complexContent>
 *     &lt;extension base="{https://www.hingeto.com/xml/V0.1}Message">
 *       &lt;sequence>
 *         &lt;element name="ProductReference" type="{https://www.hingeto.com/xml/V0.1}CatalogProductReference"/>
 *         &lt;element name="ListingSource" type="{https://www.hingeto.com/xml/V0.1}ListingSource"/>
 *         &lt;element name="ListingOnlineFlag" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="InventoryData" type="{https://www.hingeto.com/xml/V0.1}InventoryData" minOccurs="0"/>
 *         &lt;element name="PriceData" type="{https://www.hingeto.com/xml/V0.1}PriceData" minOccurs="0"/>
 *         &lt;element name="ShippingData" type="{https://www.hingeto.com/xml/V0.1}ShippingData" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="action" type="{https://www.hingeto.com/xml/V0.1}MessageAction" default="update" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ListingMessage", propOrder = {
    "productReference",
    "listingSource",
    "listingOnlineFlag",
    "inventoryData",
    "priceData",
    "shippingData"
})
public class ListingMessage
    extends Message
{

    @XmlElement(name = "ProductReference", required = true)
    protected CatalogProductReference productReference;
    @XmlElement(name = "ListingSource", required = true)
    protected ListingSource listingSource;
    @XmlElement(name = "ListingOnlineFlag")
    protected boolean listingOnlineFlag;
    @XmlElement(name = "InventoryData")
    protected InventoryData inventoryData;
    @XmlElement(name = "PriceData")
    protected PriceData priceData;
    @XmlElement(name = "ShippingData")
    protected ShippingData shippingData;
    @XmlAttribute(name = "action")
    protected MessageAction action;

    /**
     * Gets the value of the productReference property.
     * 
     * @return
     *     possible object is
     *     {@link CatalogProductReference }
     *     
     */
    public CatalogProductReference getProductReference() {
        return productReference;
    }

    /**
     * Sets the value of the productReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link CatalogProductReference }
     *     
     */
    public void setProductReference(CatalogProductReference value) {
        this.productReference = value;
    }

    /**
     * Gets the value of the listingSource property.
     * 
     * @return
     *     possible object is
     *     {@link ListingSource }
     *     
     */
    public ListingSource getListingSource() {
        return listingSource;
    }

    /**
     * Sets the value of the listingSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListingSource }
     *     
     */
    public void setListingSource(ListingSource value) {
        this.listingSource = value;
    }

    /**
     * Gets the value of the listingOnlineFlag property.
     * 
     */
    public boolean isListingOnlineFlag() {
        return listingOnlineFlag;
    }

    /**
     * Sets the value of the listingOnlineFlag property.
     * 
     */
    public void setListingOnlineFlag(boolean value) {
        this.listingOnlineFlag = value;
    }

    /**
     * Gets the value of the inventoryData property.
     * 
     * @return
     *     possible object is
     *     {@link InventoryData }
     *     
     */
    public InventoryData getInventoryData() {
        return inventoryData;
    }

    /**
     * Sets the value of the inventoryData property.
     * 
     * @param value
     *     allowed object is
     *     {@link InventoryData }
     *     
     */
    public void setInventoryData(InventoryData value) {
        this.inventoryData = value;
    }

    /**
     * Gets the value of the priceData property.
     * 
     * @return
     *     possible object is
     *     {@link PriceData }
     *     
     */
    public PriceData getPriceData() {
        return priceData;
    }

    /**
     * Sets the value of the priceData property.
     * 
     * @param value
     *     allowed object is
     *     {@link PriceData }
     *     
     */
    public void setPriceData(PriceData value) {
        this.priceData = value;
    }

    /**
     * Gets the value of the shippingData property.
     * 
     * @return
     *     possible object is
     *     {@link ShippingData }
     *     
     */
    public ShippingData getShippingData() {
        return shippingData;
    }

    /**
     * Sets the value of the shippingData property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShippingData }
     *     
     */
    public void setShippingData(ShippingData value) {
        this.shippingData = value;
    }

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link MessageAction }
     *     
     */
    public MessageAction getAction() {
        if (action == null) {
            return MessageAction.UPDATE;
        } else {
            return action;
        }
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageAction }
     *     
     */
    public void setAction(MessageAction value) {
        this.action = value;
    }

}
