//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.30 at 06:38:40 PM PDT 
//


package com.hingeto.api;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.hingeto.api package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.hingeto.api
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link NamedLocalizedAttributeList }
     * 
     */
    public NamedLocalizedAttributeList createNamedLocalizedAttributeList() {
        return new NamedLocalizedAttributeList();
    }

    /**
     * Create an instance of {@link NamedLocalizedAttribute }
     * 
     */
    public NamedLocalizedAttribute createNamedLocalizedAttribute() {
        return new NamedLocalizedAttribute();
    }

    /**
     * Create an instance of {@link NamedAttributeList }
     * 
     */
    public NamedAttributeList createNamedAttributeList() {
        return new NamedAttributeList();
    }

    /**
     * Create an instance of {@link Feed }
     * 
     */
    public Feed createFeed() {
        return new Feed();
    }

    /**
     * Create an instance of {@link Header }
     * 
     */
    public Header createHeader() {
        return new Header();
    }

    /**
     * Create an instance of {@link ProductContentList }
     * 
     */
    public ProductContentList createProductContentList() {
        return new ProductContentList();
    }

    /**
     * Create an instance of {@link ImageURLList }
     * 
     */
    public ImageURLList createImageURLList() {
        return new ImageURLList();
    }

    /**
     * Create an instance of {@link CategoryAssignmentList }
     * 
     */
    public CategoryAssignmentList createCategoryAssignmentList() {
        return new CategoryAssignmentList();
    }

    /**
     * Create an instance of {@link ListingList }
     * 
     */
    public ListingList createListingList() {
        return new ListingList();
    }

    /**
     * Create an instance of {@link FullProductList }
     * 
     */
    public FullProductList createFullProductList() {
        return new FullProductList();
    }

    /**
     * Create an instance of {@link OrderList }
     * 
     */
    public OrderList createOrderList() {
        return new OrderList();
    }

    /**
     * Create an instance of {@link RMAList }
     * 
     */
    public RMAList createRMAList() {
        return new RMAList();
    }

    /**
     * Create an instance of {@link RefundRequestList }
     * 
     */
    public RefundRequestList createRefundRequestList() {
        return new RefundRequestList();
    }

    /**
     * Create an instance of {@link RefundList }
     * 
     */
    public RefundList createRefundList() {
        return new RefundList();
    }

    /**
     * Create an instance of {@link ReturnList }
     * 
     */
    public ReturnList createReturnList() {
        return new ReturnList();
    }

    /**
     * Create an instance of {@link OrderStatusList }
     * 
     */
    public OrderStatusList createOrderStatusList() {
        return new OrderStatusList();
    }

    /**
     * Create an instance of {@link StorefrontTree }
     * 
     */
    public StorefrontTree createStorefrontTree() {
        return new StorefrontTree();
    }

    /**
     * Create an instance of {@link ShippingCalculationList }
     * 
     */
    public ShippingCalculationList createShippingCalculationList() {
        return new ShippingCalculationList();
    }

    /**
     * Create an instance of {@link ProcessingResponse }
     * 
     */
    public ProcessingResponse createProcessingResponse() {
        return new ProcessingResponse();
    }

    /**
     * Create an instance of {@link NewProductAuthorizationResponse }
     * 
     */
    public NewProductAuthorizationResponse createNewProductAuthorizationResponse() {
        return new NewProductAuthorizationResponse();
    }

    /**
     * Create an instance of {@link ProductResponse }
     * 
     */
    public ProductResponse createProductResponse() {
        return new ProductResponse();
    }

    /**
     * Create an instance of {@link ListingResponse }
     * 
     */
    public ListingResponse createListingResponse() {
        return new ListingResponse();
    }

    /**
     * Create an instance of {@link SupplierList }
     * 
     */
    public SupplierList createSupplierList() {
        return new SupplierList();
    }

    /**
     * Create an instance of {@link SupplierCommissionList }
     * 
     */
    public SupplierCommissionList createSupplierCommissionList() {
        return new SupplierCommissionList();
    }

    /**
     * Create an instance of {@link ValidationResults }
     * 
     */
    public ValidationResults createValidationResults() {
        return new ValidationResults();
    }

    /**
     * Create an instance of {@link SupplierAttribute }
     * 
     */
    public SupplierAttribute createSupplierAttribute() {
        return new SupplierAttribute();
    }

    /**
     * Create an instance of {@link CancellationItem }
     * 
     */
    public CancellationItem createCancellationItem() {
        return new CancellationItem();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link ReturnMessage }
     * 
     */
    public ReturnMessage createReturnMessage() {
        return new ReturnMessage();
    }

    /**
     * Create an instance of {@link FeedResponse }
     * 
     */
    public FeedResponse createFeedResponse() {
        return new FeedResponse();
    }

    /**
     * Create an instance of {@link VariationTheme }
     * 
     */
    public VariationTheme createVariationTheme() {
        return new VariationTheme();
    }

    /**
     * Create an instance of {@link ProductMessage }
     * 
     */
    public ProductMessage createProductMessage() {
        return new ProductMessage();
    }

    /**
     * Create an instance of {@link RefundRejectionMessage }
     * 
     */
    public RefundRejectionMessage createRefundRejectionMessage() {
        return new RefundRejectionMessage();
    }

    /**
     * Create an instance of {@link CustomAttributes }
     * 
     */
    public CustomAttributes createCustomAttributes() {
        return new CustomAttributes();
    }

    /**
     * Create an instance of {@link ImageURLData }
     * 
     */
    public ImageURLData createImageURLData() {
        return new ImageURLData();
    }

    /**
     * Create an instance of {@link ShippingBand }
     * 
     */
    public ShippingBand createShippingBand() {
        return new ShippingBand();
    }

    /**
     * Create an instance of {@link SupplierCommissionMessage }
     * 
     */
    public SupplierCommissionMessage createSupplierCommissionMessage() {
        return new SupplierCommissionMessage();
    }

    /**
     * Create an instance of {@link DisposalFeeType }
     * 
     */
    public DisposalFeeType createDisposalFeeType() {
        return new DisposalFeeType();
    }

    /**
     * Create an instance of {@link ContentMessage }
     * 
     */
    public ContentMessage createContentMessage() {
        return new ContentMessage();
    }

    /**
     * Create an instance of {@link ShippingPrice }
     * 
     */
    public ShippingPrice createShippingPrice() {
        return new ShippingPrice();
    }

    /**
     * Create an instance of {@link OrderState }
     * 
     */
    public OrderState createOrderState() {
        return new OrderState();
    }

    /**
     * Create an instance of {@link StateItem }
     * 
     */
    public StateItem createStateItem() {
        return new StateItem();
    }

    /**
     * Create an instance of {@link RMAItem }
     * 
     */
    public RMAItem createRMAItem() {
        return new RMAItem();
    }

    /**
     * Create an instance of {@link ListingMessage }
     * 
     */
    public ListingMessage createListingMessage() {
        return new ListingMessage();
    }

    /**
     * Create an instance of {@link NewProductAuthorizationResponseContent }
     * 
     */
    public NewProductAuthorizationResponseContent createNewProductAuthorizationResponseContent() {
        return new NewProductAuthorizationResponseContent();
    }

    /**
     * Create an instance of {@link BillingData }
     * 
     */
    public BillingData createBillingData() {
        return new BillingData();
    }

    /**
     * Create an instance of {@link ProductLocalizedAttribute }
     * 
     */
    public ProductLocalizedAttribute createProductLocalizedAttribute() {
        return new ProductLocalizedAttribute();
    }

    /**
     * Create an instance of {@link ProductAttribute }
     * 
     */
    public ProductAttribute createProductAttribute() {
        return new ProductAttribute();
    }

    /**
     * Create an instance of {@link RefundConfirmationMessage }
     * 
     */
    public RefundConfirmationMessage createRefundConfirmationMessage() {
        return new RefundConfirmationMessage();
    }

    /**
     * Create an instance of {@link OrderStatusMessage }
     * 
     */
    public OrderStatusMessage createOrderStatusMessage() {
        return new OrderStatusMessage();
    }

    /**
     * Create an instance of {@link OrderAttribute }
     * 
     */
    public OrderAttribute createOrderAttribute() {
        return new OrderAttribute();
    }

    /**
     * Create an instance of {@link Supplier }
     * 
     */
    public Supplier createSupplier() {
        return new Supplier();
    }

    /**
     * Create an instance of {@link ValidationHeader }
     * 
     */
    public ValidationHeader createValidationHeader() {
        return new ValidationHeader();
    }

    /**
     * Create an instance of {@link ProductData }
     * 
     */
    public ProductData createProductData() {
        return new ProductData();
    }

    /**
     * Create an instance of {@link OrderFulfillment }
     * 
     */
    public OrderFulfillment createOrderFulfillment() {
        return new OrderFulfillment();
    }

    /**
     * Create an instance of {@link Dimensions }
     * 
     */
    public Dimensions createDimensions() {
        return new Dimensions();
    }

    /**
     * Create an instance of {@link OrderItemPrices }
     * 
     */
    public OrderItemPrices createOrderItemPrices() {
        return new OrderItemPrices();
    }

    /**
     * Create an instance of {@link NewProductAuthorizationResponseItem }
     * 
     */
    public NewProductAuthorizationResponseItem createNewProductAuthorizationResponseItem() {
        return new NewProductAuthorizationResponseItem();
    }

    /**
     * Create an instance of {@link RefundMessage }
     * 
     */
    public RefundMessage createRefundMessage() {
        return new RefundMessage();
    }

    /**
     * Create an instance of {@link CurrencyPrice }
     * 
     */
    public CurrencyPrice createCurrencyPrice() {
        return new CurrencyPrice();
    }

    /**
     * Create an instance of {@link OrderItemPrice }
     * 
     */
    public OrderItemPrice createOrderItemPrice() {
        return new OrderItemPrice();
    }

    /**
     * Create an instance of {@link OrderItem }
     * 
     */
    public OrderItem createOrderItem() {
        return new OrderItem();
    }

    /**
     * Create an instance of {@link FullProductMessage }
     * 
     */
    public FullProductMessage createFullProductMessage() {
        return new FullProductMessage();
    }

    /**
     * Create an instance of {@link VariationAttributeName }
     * 
     */
    public VariationAttributeName createVariationAttributeName() {
        return new VariationAttributeName();
    }

    /**
     * Create an instance of {@link NamedAttribute }
     * 
     */
    public NamedAttribute createNamedAttribute() {
        return new NamedAttribute();
    }

    /**
     * Create an instance of {@link ProductAttributeList }
     * 
     */
    public ProductAttributeList createProductAttributeList() {
        return new ProductAttributeList();
    }

    /**
     * Create an instance of {@link StorefrontCategory }
     * 
     */
    public StorefrontCategory createStorefrontCategory() {
        return new StorefrontCategory();
    }

    /**
     * Create an instance of {@link Variations }
     * 
     */
    public Variations createVariations() {
        return new Variations();
    }

    /**
     * Create an instance of {@link FulfillmentData }
     * 
     */
    public FulfillmentData createFulfillmentData() {
        return new FulfillmentData();
    }

    /**
     * Create an instance of {@link ShippingOptionMessage }
     * 
     */
    public ShippingOptionMessage createShippingOptionMessage() {
        return new ShippingOptionMessage();
    }

    /**
     * Create an instance of {@link RefundProcessingMessage }
     * 
     */
    public RefundProcessingMessage createRefundProcessingMessage() {
        return new RefundProcessingMessage();
    }

    /**
     * Create an instance of {@link ImageURLMessage }
     * 
     */
    public ImageURLMessage createImageURLMessage() {
        return new ImageURLMessage();
    }

    /**
     * Create an instance of {@link SupplierAttributes }
     * 
     */
    public SupplierAttributes createSupplierAttributes() {
        return new SupplierAttributes();
    }

    /**
     * Create an instance of {@link ResponseItem }
     * 
     */
    public ResponseItem createResponseItem() {
        return new ResponseItem();
    }

    /**
     * Create an instance of {@link ShippingData }
     * 
     */
    public ShippingData createShippingData() {
        return new ShippingData();
    }

    /**
     * Create an instance of {@link ValidationResult }
     * 
     */
    public ValidationResult createValidationResult() {
        return new ValidationResult();
    }

    /**
     * Create an instance of {@link ValidationMessage }
     * 
     */
    public ValidationMessage createValidationMessage() {
        return new ValidationMessage();
    }

    /**
     * Create an instance of {@link ImageURL }
     * 
     */
    public ImageURL createImageURL() {
        return new ImageURL();
    }

    /**
     * Create an instance of {@link CatalogProductReference }
     * 
     */
    public CatalogProductReference createCatalogProductReference() {
        return new CatalogProductReference();
    }

    /**
     * Create an instance of {@link RMAMessage }
     * 
     */
    public RMAMessage createRMAMessage() {
        return new RMAMessage();
    }

    /**
     * Create an instance of {@link InventoryData }
     * 
     */
    public InventoryData createInventoryData() {
        return new InventoryData();
    }

    /**
     * Create an instance of {@link ListingSource }
     * 
     */
    public ListingSource createListingSource() {
        return new ListingSource();
    }

    /**
     * Create an instance of {@link OrderAttributes }
     * 
     */
    public OrderAttributes createOrderAttributes() {
        return new OrderAttributes();
    }

    /**
     * Create an instance of {@link ProductResponseItem }
     * 
     */
    public ProductResponseItem createProductResponseItem() {
        return new ProductResponseItem();
    }

    /**
     * Create an instance of {@link ProductSuppliers }
     * 
     */
    public ProductSuppliers createProductSuppliers() {
        return new ProductSuppliers();
    }

    /**
     * Create an instance of {@link OrderCancellation }
     * 
     */
    public OrderCancellation createOrderCancellation() {
        return new OrderCancellation();
    }

    /**
     * Create an instance of {@link SalePrice }
     * 
     */
    public SalePrice createSalePrice() {
        return new SalePrice();
    }

    /**
     * Create an instance of {@link Message }
     * 
     */
    public Message createMessage() {
        return new Message();
    }

    /**
     * Create an instance of {@link PriceData }
     * 
     */
    public PriceData createPriceData() {
        return new PriceData();
    }

    /**
     * Create an instance of {@link CustomAttribute }
     * 
     */
    public CustomAttribute createCustomAttribute() {
        return new CustomAttribute();
    }

    /**
     * Create an instance of {@link ProductIDs }
     * 
     */
    public ProductIDs createProductIDs() {
        return new ProductIDs();
    }

    /**
     * Create an instance of {@link ListingResponseItemType }
     * 
     */
    public ListingResponseItemType createListingResponseItemType() {
        return new ListingResponseItemType();
    }

    /**
     * Create an instance of {@link CategoryAssignmentMessage }
     * 
     */
    public CategoryAssignmentMessage createCategoryAssignmentMessage() {
        return new CategoryAssignmentMessage();
    }

    /**
     * Create an instance of {@link ProductLocalizedAttributeList }
     * 
     */
    public ProductLocalizedAttributeList createProductLocalizedAttributeList() {
        return new ProductLocalizedAttributeList();
    }

    /**
     * Create an instance of {@link Condition }
     * 
     */
    public Condition createCondition() {
        return new Condition();
    }

    /**
     * Create an instance of {@link VariationChildren }
     * 
     */
    public VariationChildren createVariationChildren() {
        return new VariationChildren();
    }

    /**
     * Create an instance of {@link ProductContentType }
     * 
     */
    public ProductContentType createProductContentType() {
        return new ProductContentType();
    }

    /**
     * Create an instance of {@link ListingIDType }
     * 
     */
    public ListingIDType createListingIDType() {
        return new ListingIDType();
    }

    /**
     * Create an instance of {@link SalesOrderMessage }
     * 
     */
    public SalesOrderMessage createSalesOrderMessage() {
        return new SalesOrderMessage();
    }

    /**
     * Create an instance of {@link RefundRequestMessage }
     * 
     */
    public RefundRequestMessage createRefundRequestMessage() {
        return new RefundRequestMessage();
    }

    /**
     * Create an instance of {@link FulfillmentItem }
     * 
     */
    public FulfillmentItem createFulfillmentItem() {
        return new FulfillmentItem();
    }

    /**
     * Create an instance of {@link DataID }
     * 
     */
    public DataID createDataID() {
        return new DataID();
    }

    /**
     * Create an instance of {@link SupplierMessage }
     * 
     */
    public SupplierMessage createSupplierMessage() {
        return new SupplierMessage();
    }

    /**
     * Create an instance of {@link CategoryCommissionType }
     * 
     */
    public CategoryCommissionType createCategoryCommissionType() {
        return new CategoryCommissionType();
    }

    /**
     * Create an instance of {@link CategoryAssignment }
     * 
     */
    public CategoryAssignment createCategoryAssignment() {
        return new CategoryAssignment();
    }

    /**
     * Create an instance of {@link ShippingModel }
     * 
     */
    public ShippingModel createShippingModel() {
        return new ShippingModel();
    }

    /**
     * Create an instance of {@link CategoryName }
     * 
     */
    public CategoryName createCategoryName() {
        return new CategoryName();
    }

    /**
     * Create an instance of {@link CategoryAssignmentData }
     * 
     */
    public CategoryAssignmentData createCategoryAssignmentData() {
        return new CategoryAssignmentData();
    }

    /**
     * Create an instance of {@link NamedLocalizedAttributeList.Values }
     * 
     */
    public NamedLocalizedAttributeList.Values createNamedLocalizedAttributeListValues() {
        return new NamedLocalizedAttributeList.Values();
    }

    /**
     * Create an instance of {@link NamedLocalizedAttribute.Value }
     * 
     */
    public NamedLocalizedAttribute.Value createNamedLocalizedAttributeValue() {
        return new NamedLocalizedAttribute.Value();
    }

    /**
     * Create an instance of {@link NamedAttributeList.Values }
     * 
     */
    public NamedAttributeList.Values createNamedAttributeListValues() {
        return new NamedAttributeList.Values();
    }

}
