//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.30 at 06:38:40 PM PDT 
//


package com.hingeto.api;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OrderItem complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OrderItem">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="OrderItemCode" type="{https://www.hingeto.com/xml/V0.1}OrderItemCode"/>
 *         &lt;element name="StoreFrontLineItemID" type="{https://www.hingeto.com/xml/V0.1}StoreFrontLineItem"/>
 *         &lt;element name="OrderItemStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ListingID" type="{https://www.hingeto.com/xml/V0.1}ListingIDType"/>
 *         &lt;element name="Title" type="{https://www.hingeto.com/xml/V0.1}String255" minOccurs="0"/>
 *         &lt;element name="Quantity" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="GiftWrapLevel" type="{https://www.hingeto.com/xml/V0.1}String255" minOccurs="0"/>
 *         &lt;element name="GiftMessageText" type="{https://www.hingeto.com/xml/V0.1}String255" minOccurs="0"/>
 *         &lt;element name="ItemPrices" type="{https://www.hingeto.com/xml/V0.1}OrderItemPrices"/>
 *         &lt;element name="ItemDiscounts" type="{https://www.hingeto.com/xml/V0.1}OrderItemPrices" minOccurs="0"/>
 *         &lt;element name="ItemAttributes" type="{https://www.hingeto.com/xml/V0.1}OrderAttributes" minOccurs="0"/>
 *         &lt;element name="ShippingAddress" type="{https://www.hingeto.com/xml/V0.1}Address" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OrderItem", propOrder = {
    "orderItemCode",
    "storeFrontLineItemID",
    "orderItemStatus",
    "listingID",
    "title",
    "quantity",
    "giftWrapLevel",
    "giftMessageText",
    "itemPrices",
    "itemDiscounts",
    "itemAttributes",
    "shippingAddress"
})
public class OrderItem {

    @XmlElement(name = "OrderItemCode", required = true)
    protected String orderItemCode;
    @XmlElement(name = "StoreFrontLineItemID", required = true)
    protected String storeFrontLineItemID;
    @XmlElement(name = "OrderItemStatus")
    protected String orderItemStatus;
    @XmlElement(name = "ListingID", required = true)
    protected ListingIDType listingID;
    @XmlElement(name = "Title")
    protected String title;
    @XmlElement(name = "Quantity", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger quantity;
    @XmlElement(name = "GiftWrapLevel")
    protected String giftWrapLevel;
    @XmlElement(name = "GiftMessageText")
    protected String giftMessageText;
    @XmlElement(name = "ItemPrices", required = true)
    protected OrderItemPrices itemPrices;
    @XmlElement(name = "ItemDiscounts")
    protected OrderItemPrices itemDiscounts;
    @XmlElement(name = "ItemAttributes")
    protected OrderAttributes itemAttributes;
    @XmlElement(name = "ShippingAddress")
    protected Address shippingAddress;

    /**
     * Gets the value of the orderItemCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderItemCode() {
        return orderItemCode;
    }

    /**
     * Sets the value of the orderItemCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderItemCode(String value) {
        this.orderItemCode = value;
    }

    /**
     * Gets the value of the storeFrontLineItemID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStoreFrontLineItemID() {
        return storeFrontLineItemID;
    }

    /**
     * Sets the value of the storeFrontLineItemID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStoreFrontLineItemID(String value) {
        this.storeFrontLineItemID = value;
    }

    /**
     * Gets the value of the orderItemStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderItemStatus() {
        return orderItemStatus;
    }

    /**
     * Sets the value of the orderItemStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderItemStatus(String value) {
        this.orderItemStatus = value;
    }

    /**
     * Gets the value of the listingID property.
     * 
     * @return
     *     possible object is
     *     {@link ListingIDType }
     *     
     */
    public ListingIDType getListingID() {
        return listingID;
    }

    /**
     * Sets the value of the listingID property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListingIDType }
     *     
     */
    public void setListingID(ListingIDType value) {
        this.listingID = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the quantity property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getQuantity() {
        return quantity;
    }

    /**
     * Sets the value of the quantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setQuantity(BigInteger value) {
        this.quantity = value;
    }

    /**
     * Gets the value of the giftWrapLevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGiftWrapLevel() {
        return giftWrapLevel;
    }

    /**
     * Sets the value of the giftWrapLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGiftWrapLevel(String value) {
        this.giftWrapLevel = value;
    }

    /**
     * Gets the value of the giftMessageText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGiftMessageText() {
        return giftMessageText;
    }

    /**
     * Sets the value of the giftMessageText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGiftMessageText(String value) {
        this.giftMessageText = value;
    }

    /**
     * Gets the value of the itemPrices property.
     * 
     * @return
     *     possible object is
     *     {@link OrderItemPrices }
     *     
     */
    public OrderItemPrices getItemPrices() {
        return itemPrices;
    }

    /**
     * Sets the value of the itemPrices property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderItemPrices }
     *     
     */
    public void setItemPrices(OrderItemPrices value) {
        this.itemPrices = value;
    }

    /**
     * Gets the value of the itemDiscounts property.
     * 
     * @return
     *     possible object is
     *     {@link OrderItemPrices }
     *     
     */
    public OrderItemPrices getItemDiscounts() {
        return itemDiscounts;
    }

    /**
     * Sets the value of the itemDiscounts property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderItemPrices }
     *     
     */
    public void setItemDiscounts(OrderItemPrices value) {
        this.itemDiscounts = value;
    }

    /**
     * Gets the value of the itemAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link OrderAttributes }
     *     
     */
    public OrderAttributes getItemAttributes() {
        return itemAttributes;
    }

    /**
     * Sets the value of the itemAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderAttributes }
     *     
     */
    public void setItemAttributes(OrderAttributes value) {
        this.itemAttributes = value;
    }

    /**
     * Gets the value of the shippingAddress property.
     * 
     * @return
     *     possible object is
     *     {@link Address }
     *     
     */
    public Address getShippingAddress() {
        return shippingAddress;
    }

    /**
     * Sets the value of the shippingAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link Address }
     *     
     */
    public void setShippingAddress(Address value) {
        this.shippingAddress = value;
    }

}
