//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.30 at 06:38:40 PM PDT 
//


package com.hingeto.api;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for OrderStatusMessage complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OrderStatusMessage">
 *   &lt;complexContent>
 *     &lt;extension base="{https://www.hingeto.com/xml/V0.1}Message">
 *       &lt;sequence>
 *         &lt;element name="OrderID" type="{https://www.hingeto.com/xml/V0.1}OrderID"/>
 *         &lt;element name="PONumber" type="{https://www.hingeto.com/xml/V0.1}String255"/>
 *         &lt;element name="StatusUpdateDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;choice>
 *           &lt;element name="OrderFulfillment" type="{https://www.hingeto.com/xml/V0.1}OrderFulfillment"/>
 *           &lt;element name="OrderCancellation" type="{https://www.hingeto.com/xml/V0.1}OrderCancellation"/>
 *           &lt;element name="OrderState" type="{https://www.hingeto.com/xml/V0.1}OrderState"/>
 *         &lt;/choice>
 *         &lt;element name="OrderStatusAttributes" type="{https://www.hingeto.com/xml/V0.1}OrderAttributes" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OrderStatusMessage", propOrder = {
    "orderID",
    "poNumber",
    "statusUpdateDate",
    "orderFulfillment",
    "orderCancellation",
    "orderState",
    "orderStatusAttributes"
})
public class OrderStatusMessage
    extends Message
{

    @XmlElement(name = "OrderID", required = true)
    protected String orderID;
    @XmlElement(name = "PONumber", required = true)
    protected String poNumber;
    @XmlElement(name = "StatusUpdateDate", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar statusUpdateDate;
    @XmlElement(name = "OrderFulfillment")
    protected OrderFulfillment orderFulfillment;
    @XmlElement(name = "OrderCancellation")
    protected OrderCancellation orderCancellation;
    @XmlElement(name = "OrderState")
    protected OrderState orderState;
    @XmlElement(name = "OrderStatusAttributes")
    protected OrderAttributes orderStatusAttributes;

    /**
     * Gets the value of the orderID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderID() {
        return orderID;
    }

    /**
     * Sets the value of the orderID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderID(String value) {
        this.orderID = value;
    }

    /**
     * Gets the value of the poNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPONumber() {
        return poNumber;
    }

    /**
     * Sets the value of the poNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPONumber(String value) {
        this.poNumber = value;
    }

    /**
     * Gets the value of the statusUpdateDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStatusUpdateDate() {
        return statusUpdateDate;
    }

    /**
     * Sets the value of the statusUpdateDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStatusUpdateDate(XMLGregorianCalendar value) {
        this.statusUpdateDate = value;
    }

    /**
     * Gets the value of the orderFulfillment property.
     * 
     * @return
     *     possible object is
     *     {@link OrderFulfillment }
     *     
     */
    public OrderFulfillment getOrderFulfillment() {
        return orderFulfillment;
    }

    /**
     * Sets the value of the orderFulfillment property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderFulfillment }
     *     
     */
    public void setOrderFulfillment(OrderFulfillment value) {
        this.orderFulfillment = value;
    }

    /**
     * Gets the value of the orderCancellation property.
     * 
     * @return
     *     possible object is
     *     {@link OrderCancellation }
     *     
     */
    public OrderCancellation getOrderCancellation() {
        return orderCancellation;
    }

    /**
     * Sets the value of the orderCancellation property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderCancellation }
     *     
     */
    public void setOrderCancellation(OrderCancellation value) {
        this.orderCancellation = value;
    }

    /**
     * Gets the value of the orderState property.
     * 
     * @return
     *     possible object is
     *     {@link OrderState }
     *     
     */
    public OrderState getOrderState() {
        return orderState;
    }

    /**
     * Sets the value of the orderState property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderState }
     *     
     */
    public void setOrderState(OrderState value) {
        this.orderState = value;
    }

    /**
     * Gets the value of the orderStatusAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link OrderAttributes }
     *     
     */
    public OrderAttributes getOrderStatusAttributes() {
        return orderStatusAttributes;
    }

    /**
     * Sets the value of the orderStatusAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderAttributes }
     *     
     */
    public void setOrderStatusAttributes(OrderAttributes value) {
        this.orderStatusAttributes = value;
    }

}
