//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.30 at 06:38:40 PM PDT 
//


package com.hingeto.api;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OrderItemPriceType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="OrderItemPriceType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ItemPrice"/>
 *     &lt;enumeration value="ItemTax"/>
 *     &lt;enumeration value="ShippingPrice"/>
 *     &lt;enumeration value="ShippingTax"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "OrderItemPriceType")
@XmlEnum
public enum OrderItemPriceType {

    @XmlEnumValue("ItemPrice")
    ITEM_PRICE("ItemPrice"),
    @XmlEnumValue("ItemTax")
    ITEM_TAX("ItemTax"),
    @XmlEnumValue("ShippingPrice")
    SHIPPING_PRICE("ShippingPrice"),
    @XmlEnumValue("ShippingTax")
    SHIPPING_TAX("ShippingTax");
    private final String value;

    OrderItemPriceType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static OrderItemPriceType fromValue(String v) {
        for (OrderItemPriceType c: OrderItemPriceType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
