//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.30 at 06:38:40 PM PDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "https://www.hingeto.com/xml/V0.1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.hingeto.api;
