//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.30 at 06:38:40 PM PDT 
//


package com.hingeto.api;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PriceData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PriceData">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TaxClass" type="{https://www.hingeto.com/xml/V0.1}TaxClassType" minOccurs="0"/>
 *         &lt;element name="DisposalFee" type="{https://www.hingeto.com/xml/V0.1}DisposalFeeType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ListPrice" type="{https://www.hingeto.com/xml/V0.1}CurrencyPrice" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="MSRP" type="{https://www.hingeto.com/xml/V0.1}CurrencyPrice" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="SalePrice" type="{https://www.hingeto.com/xml/V0.1}SalePrice" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="BasicCost" type="{https://www.hingeto.com/xml/V0.1}CurrencyPrice" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="StrikeThroughPrice" type="{https://www.hingeto.com/xml/V0.1}CurrencyPrice" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="MAPPrice" type="{https://www.hingeto.com/xml/V0.1}CurrencyPrice" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="DropshipFee" type="{https://www.hingeto.com/xml/V0.1}CurrencyPrice" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="CustomAttributes" type="{https://www.hingeto.com/xml/V0.1}CustomAttributes" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PriceData", propOrder = {
    "taxClass",
    "disposalFee",
    "listPrice",
    "msrp",
    "salePrice",
    "basicCost",
    "strikeThroughPrice",
    "mapPrice",
    "dropshipFee",
    "customAttributes"
})
public class PriceData {

    @XmlElement(name = "TaxClass")
    protected String taxClass;
    @XmlElement(name = "DisposalFee")
    protected List<DisposalFeeType> disposalFee;
    @XmlElement(name = "ListPrice")
    protected List<CurrencyPrice> listPrice;
    @XmlElement(name = "MSRP")
    protected List<CurrencyPrice> msrp;
    @XmlElement(name = "SalePrice")
    protected List<SalePrice> salePrice;
    @XmlElement(name = "BasicCost")
    protected List<CurrencyPrice> basicCost;
    @XmlElement(name = "StrikeThroughPrice")
    protected List<CurrencyPrice> strikeThroughPrice;
    @XmlElement(name = "MAPPrice")
    protected List<CurrencyPrice> mapPrice;
    @XmlElement(name = "DropshipFee")
    protected List<CurrencyPrice> dropshipFee;
    @XmlElement(name = "CustomAttributes")
    protected CustomAttributes customAttributes;

    /**
     * Gets the value of the taxClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxClass() {
        return taxClass;
    }

    /**
     * Sets the value of the taxClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxClass(String value) {
        this.taxClass = value;
    }

    /**
     * Gets the value of the disposalFee property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the disposalFee property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDisposalFee().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DisposalFeeType }
     * 
     * 
     */
    public List<DisposalFeeType> getDisposalFee() {
        if (disposalFee == null) {
            disposalFee = new ArrayList<DisposalFeeType>();
        }
        return this.disposalFee;
    }

    /**
     * Gets the value of the listPrice property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the listPrice property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getListPrice().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CurrencyPrice }
     * 
     * 
     */
    public List<CurrencyPrice> getListPrice() {
        if (listPrice == null) {
            listPrice = new ArrayList<CurrencyPrice>();
        }
        return this.listPrice;
    }

    /**
     * Gets the value of the msrp property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the msrp property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMSRP().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CurrencyPrice }
     * 
     * 
     */
    public List<CurrencyPrice> getMSRP() {
        if (msrp == null) {
            msrp = new ArrayList<CurrencyPrice>();
        }
        return this.msrp;
    }

    /**
     * Gets the value of the salePrice property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the salePrice property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSalePrice().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SalePrice }
     * 
     * 
     */
    public List<SalePrice> getSalePrice() {
        if (salePrice == null) {
            salePrice = new ArrayList<SalePrice>();
        }
        return this.salePrice;
    }

    /**
     * Gets the value of the basicCost property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the basicCost property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBasicCost().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CurrencyPrice }
     * 
     * 
     */
    public List<CurrencyPrice> getBasicCost() {
        if (basicCost == null) {
            basicCost = new ArrayList<CurrencyPrice>();
        }
        return this.basicCost;
    }

    /**
     * Gets the value of the strikeThroughPrice property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the strikeThroughPrice property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStrikeThroughPrice().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CurrencyPrice }
     * 
     * 
     */
    public List<CurrencyPrice> getStrikeThroughPrice() {
        if (strikeThroughPrice == null) {
            strikeThroughPrice = new ArrayList<CurrencyPrice>();
        }
        return this.strikeThroughPrice;
    }

    /**
     * Gets the value of the mapPrice property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the mapPrice property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMAPPrice().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CurrencyPrice }
     * 
     * 
     */
    public List<CurrencyPrice> getMAPPrice() {
        if (mapPrice == null) {
            mapPrice = new ArrayList<CurrencyPrice>();
        }
        return this.mapPrice;
    }

    /**
     * Gets the value of the dropshipFee property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dropshipFee property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDropshipFee().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CurrencyPrice }
     * 
     * 
     */
    public List<CurrencyPrice> getDropshipFee() {
        if (dropshipFee == null) {
            dropshipFee = new ArrayList<CurrencyPrice>();
        }
        return this.dropshipFee;
    }

    /**
     * Gets the value of the customAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link CustomAttributes }
     *     
     */
    public CustomAttributes getCustomAttributes() {
        return customAttributes;
    }

    /**
     * Sets the value of the customAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomAttributes }
     *     
     */
    public void setCustomAttributes(CustomAttributes value) {
        this.customAttributes = value;
    }

}
