//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.30 at 06:38:40 PM PDT 
//


package com.hingeto.api;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ProcessingResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProcessingResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ResponseItem" type="{https://www.hingeto.com/xml/V0.1}ResponseItem" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="FeedResponse" type="{https://www.hingeto.com/xml/V0.1}FeedResponse" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProcessingResponse", propOrder = {
    "responseItem",
    "feedResponse"
})
public class ProcessingResponse {

    @XmlElement(name = "ResponseItem")
    protected List<ResponseItem> responseItem;
    @XmlElement(name = "FeedResponse")
    protected FeedResponse feedResponse;

    /**
     * Gets the value of the responseItem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the responseItem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getResponseItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ResponseItem }
     * 
     * 
     */
    public List<ResponseItem> getResponseItem() {
        if (responseItem == null) {
            responseItem = new ArrayList<ResponseItem>();
        }
        return this.responseItem;
    }

    /**
     * Gets the value of the feedResponse property.
     * 
     * @return
     *     possible object is
     *     {@link FeedResponse }
     *     
     */
    public FeedResponse getFeedResponse() {
        return feedResponse;
    }

    /**
     * Sets the value of the feedResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link FeedResponse }
     *     
     */
    public void setFeedResponse(FeedResponse value) {
        this.feedResponse = value;
    }

}
