//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.30 at 06:38:40 PM PDT 
//


package com.hingeto.api;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ProductContentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProductContentType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="OnlineFlag" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="ProductData" type="{https://www.hingeto.com/xml/V0.1}ProductData" minOccurs="0"/>
 *         &lt;element name="ImageURLData" type="{https://www.hingeto.com/xml/V0.1}ImageURLData" minOccurs="0"/>
 *         &lt;element name="CategoryAssignmentData" type="{https://www.hingeto.com/xml/V0.1}CategoryAssignmentData" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProductContentType", propOrder = {
    "onlineFlag",
    "productData",
    "imageURLData",
    "categoryAssignmentData"
})
public class ProductContentType {

    @XmlElement(name = "OnlineFlag")
    protected boolean onlineFlag;
    @XmlElement(name = "ProductData")
    protected ProductData productData;
    @XmlElement(name = "ImageURLData")
    protected ImageURLData imageURLData;
    @XmlElement(name = "CategoryAssignmentData")
    protected CategoryAssignmentData categoryAssignmentData;

    /**
     * Gets the value of the onlineFlag property.
     * 
     */
    public boolean isOnlineFlag() {
        return onlineFlag;
    }

    /**
     * Sets the value of the onlineFlag property.
     * 
     */
    public void setOnlineFlag(boolean value) {
        this.onlineFlag = value;
    }

    /**
     * Gets the value of the productData property.
     * 
     * @return
     *     possible object is
     *     {@link ProductData }
     *     
     */
    public ProductData getProductData() {
        return productData;
    }

    /**
     * Sets the value of the productData property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductData }
     *     
     */
    public void setProductData(ProductData value) {
        this.productData = value;
    }

    /**
     * Gets the value of the imageURLData property.
     * 
     * @return
     *     possible object is
     *     {@link ImageURLData }
     *     
     */
    public ImageURLData getImageURLData() {
        return imageURLData;
    }

    /**
     * Sets the value of the imageURLData property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImageURLData }
     *     
     */
    public void setImageURLData(ImageURLData value) {
        this.imageURLData = value;
    }

    /**
     * Gets the value of the categoryAssignmentData property.
     * 
     * @return
     *     possible object is
     *     {@link CategoryAssignmentData }
     *     
     */
    public CategoryAssignmentData getCategoryAssignmentData() {
        return categoryAssignmentData;
    }

    /**
     * Sets the value of the categoryAssignmentData property.
     * 
     * @param value
     *     allowed object is
     *     {@link CategoryAssignmentData }
     *     
     */
    public void setCategoryAssignmentData(CategoryAssignmentData value) {
        this.categoryAssignmentData = value;
    }

}
