//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.30 at 06:38:40 PM PDT 
//


package com.hingeto.api;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ProductResponseItem complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProductResponseItem">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="SKU" type="{https://www.hingeto.com/xml/V0.1}ProductSKU"/>
 *           &lt;element name="StorefrontProductID" type="{https://www.hingeto.com/xml/V0.1}StorefrontProductIDType"/>
 *         &lt;/choice>
 *         &lt;element name="Result" type="{https://www.hingeto.com/xml/V0.1}ProcessingResult"/>
 *         &lt;element name="Message" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProductResponseItem", propOrder = {
    "sku",
    "storefrontProductID",
    "result",
    "message"
})
public class ProductResponseItem {

    @XmlElement(name = "SKU")
    protected String sku;
    @XmlElement(name = "StorefrontProductID")
    protected String storefrontProductID;
    @XmlElement(name = "Result", required = true)
    protected ProcessingResult result;
    @XmlElement(name = "Message")
    protected String message;

    /**
     * Gets the value of the sku property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSKU() {
        return sku;
    }

    /**
     * Sets the value of the sku property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSKU(String value) {
        this.sku = value;
    }

    /**
     * Gets the value of the storefrontProductID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStorefrontProductID() {
        return storefrontProductID;
    }

    /**
     * Sets the value of the storefrontProductID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStorefrontProductID(String value) {
        this.storefrontProductID = value;
    }

    /**
     * Gets the value of the result property.
     * 
     * @return
     *     possible object is
     *     {@link ProcessingResult }
     *     
     */
    public ProcessingResult getResult() {
        return result;
    }

    /**
     * Sets the value of the result property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProcessingResult }
     *     
     */
    public void setResult(ProcessingResult value) {
        this.result = value;
    }

    /**
     * Gets the value of the message property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessage() {
        return message;
    }

    /**
     * Sets the value of the message property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessage(String value) {
        this.message = value;
    }

}
