//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.30 at 06:38:40 PM PDT 
//


package com.hingeto.api;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ProductData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProductData">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ProductIDs" type="{https://www.hingeto.com/xml/V0.1}ProductIDs" minOccurs="0"/>
 *         &lt;element name="VariationType" type="{https://www.hingeto.com/xml/V0.1}VariationType"/>
 *         &lt;element name="Variations" type="{https://www.hingeto.com/xml/V0.1}Variations" minOccurs="0"/>
 *         &lt;element name="Title" type="{https://www.hingeto.com/xml/V0.1}NamedLocalizedAttribute"/>
 *         &lt;element name="Description" type="{https://www.hingeto.com/xml/V0.1}NamedLocalizedAttribute" minOccurs="0"/>
 *         &lt;element name="ShortDescription" type="{https://www.hingeto.com/xml/V0.1}NamedLocalizedAttribute" minOccurs="0"/>
 *         &lt;element name="BulletPoints" type="{https://www.hingeto.com/xml/V0.1}NamedLocalizedAttributeList" minOccurs="0"/>
 *         &lt;element name="Brand" type="{https://www.hingeto.com/xml/V0.1}NamedAttribute" minOccurs="0"/>
 *         &lt;element name="Manufacturer" type="{https://www.hingeto.com/xml/V0.1}NamedAttribute" minOccurs="0"/>
 *         &lt;element name="MfrPartNumber" type="{https://www.hingeto.com/xml/V0.1}NamedAttribute" minOccurs="0"/>
 *         &lt;element name="Dimensions" type="{https://www.hingeto.com/xml/V0.1}Dimensions" minOccurs="0"/>
 *         &lt;element name="Attribute" type="{https://www.hingeto.com/xml/V0.1}ProductAttribute" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="LocalizedAttribute" type="{https://www.hingeto.com/xml/V0.1}ProductLocalizedAttribute" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="AttributeList" type="{https://www.hingeto.com/xml/V0.1}ProductAttributeList" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="LocalizedAttributeList" type="{https://www.hingeto.com/xml/V0.1}ProductLocalizedAttributeList" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProductData", propOrder = {
    "productIDs",
    "variationType",
    "variations",
    "title",
    "description",
    "shortDescription",
    "bulletPoints",
    "brand",
    "manufacturer",
    "mfrPartNumber",
    "dimensions",
    "attribute",
    "localizedAttribute",
    "attributeList",
    "localizedAttributeList"
})
public class ProductData {

    @XmlElement(name = "ProductIDs")
    protected ProductIDs productIDs;
    @XmlElement(name = "VariationType", required = true)
    protected VariationType variationType;
    @XmlElement(name = "Variations")
    protected Variations variations;
    @XmlElement(name = "Title", required = true)
    protected NamedLocalizedAttribute title;
    @XmlElement(name = "Description")
    protected NamedLocalizedAttribute description;
    @XmlElement(name = "ShortDescription")
    protected NamedLocalizedAttribute shortDescription;
    @XmlElement(name = "BulletPoints")
    protected NamedLocalizedAttributeList bulletPoints;
    @XmlElement(name = "Brand")
    protected NamedAttribute brand;
    @XmlElement(name = "Manufacturer")
    protected NamedAttribute manufacturer;
    @XmlElement(name = "MfrPartNumber")
    protected NamedAttribute mfrPartNumber;
    @XmlElement(name = "Dimensions")
    protected Dimensions dimensions;
    @XmlElement(name = "Attribute")
    protected List<ProductAttribute> attribute;
    @XmlElement(name = "LocalizedAttribute")
    protected List<ProductLocalizedAttribute> localizedAttribute;
    @XmlElement(name = "AttributeList")
    protected List<ProductAttributeList> attributeList;
    @XmlElement(name = "LocalizedAttributeList")
    protected List<ProductLocalizedAttributeList> localizedAttributeList;

    /**
     * Gets the value of the productIDs property.
     * 
     * @return
     *     possible object is
     *     {@link ProductIDs }
     *     
     */
    public ProductIDs getProductIDs() {
        return productIDs;
    }

    /**
     * Sets the value of the productIDs property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductIDs }
     *     
     */
    public void setProductIDs(ProductIDs value) {
        this.productIDs = value;
    }

    /**
     * Gets the value of the variationType property.
     * 
     * @return
     *     possible object is
     *     {@link VariationType }
     *     
     */
    public VariationType getVariationType() {
        return variationType;
    }

    /**
     * Sets the value of the variationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link VariationType }
     *     
     */
    public void setVariationType(VariationType value) {
        this.variationType = value;
    }

    /**
     * Gets the value of the variations property.
     * 
     * @return
     *     possible object is
     *     {@link Variations }
     *     
     */
    public Variations getVariations() {
        return variations;
    }

    /**
     * Sets the value of the variations property.
     * 
     * @param value
     *     allowed object is
     *     {@link Variations }
     *     
     */
    public void setVariations(Variations value) {
        this.variations = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link NamedLocalizedAttribute }
     *     
     */
    public NamedLocalizedAttribute getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link NamedLocalizedAttribute }
     *     
     */
    public void setTitle(NamedLocalizedAttribute value) {
        this.title = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link NamedLocalizedAttribute }
     *     
     */
    public NamedLocalizedAttribute getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link NamedLocalizedAttribute }
     *     
     */
    public void setDescription(NamedLocalizedAttribute value) {
        this.description = value;
    }

    /**
     * Gets the value of the shortDescription property.
     * 
     * @return
     *     possible object is
     *     {@link NamedLocalizedAttribute }
     *     
     */
    public NamedLocalizedAttribute getShortDescription() {
        return shortDescription;
    }

    /**
     * Sets the value of the shortDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link NamedLocalizedAttribute }
     *     
     */
    public void setShortDescription(NamedLocalizedAttribute value) {
        this.shortDescription = value;
    }

    /**
     * Gets the value of the bulletPoints property.
     * 
     * @return
     *     possible object is
     *     {@link NamedLocalizedAttributeList }
     *     
     */
    public NamedLocalizedAttributeList getBulletPoints() {
        return bulletPoints;
    }

    /**
     * Sets the value of the bulletPoints property.
     * 
     * @param value
     *     allowed object is
     *     {@link NamedLocalizedAttributeList }
     *     
     */
    public void setBulletPoints(NamedLocalizedAttributeList value) {
        this.bulletPoints = value;
    }

    /**
     * Gets the value of the brand property.
     * 
     * @return
     *     possible object is
     *     {@link NamedAttribute }
     *     
     */
    public NamedAttribute getBrand() {
        return brand;
    }

    /**
     * Sets the value of the brand property.
     * 
     * @param value
     *     allowed object is
     *     {@link NamedAttribute }
     *     
     */
    public void setBrand(NamedAttribute value) {
        this.brand = value;
    }

    /**
     * Gets the value of the manufacturer property.
     * 
     * @return
     *     possible object is
     *     {@link NamedAttribute }
     *     
     */
    public NamedAttribute getManufacturer() {
        return manufacturer;
    }

    /**
     * Sets the value of the manufacturer property.
     * 
     * @param value
     *     allowed object is
     *     {@link NamedAttribute }
     *     
     */
    public void setManufacturer(NamedAttribute value) {
        this.manufacturer = value;
    }

    /**
     * Gets the value of the mfrPartNumber property.
     * 
     * @return
     *     possible object is
     *     {@link NamedAttribute }
     *     
     */
    public NamedAttribute getMfrPartNumber() {
        return mfrPartNumber;
    }

    /**
     * Sets the value of the mfrPartNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link NamedAttribute }
     *     
     */
    public void setMfrPartNumber(NamedAttribute value) {
        this.mfrPartNumber = value;
    }

    /**
     * Gets the value of the dimensions property.
     * 
     * @return
     *     possible object is
     *     {@link Dimensions }
     *     
     */
    public Dimensions getDimensions() {
        return dimensions;
    }

    /**
     * Sets the value of the dimensions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dimensions }
     *     
     */
    public void setDimensions(Dimensions value) {
        this.dimensions = value;
    }

    /**
     * Gets the value of the attribute property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attribute property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAttribute().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProductAttribute }
     * 
     * 
     */
    public List<ProductAttribute> getAttribute() {
        if (attribute == null) {
            attribute = new ArrayList<ProductAttribute>();
        }
        return this.attribute;
    }

    /**
     * Gets the value of the localizedAttribute property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the localizedAttribute property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLocalizedAttribute().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProductLocalizedAttribute }
     * 
     * 
     */
    public List<ProductLocalizedAttribute> getLocalizedAttribute() {
        if (localizedAttribute == null) {
            localizedAttribute = new ArrayList<ProductLocalizedAttribute>();
        }
        return this.localizedAttribute;
    }

    /**
     * Gets the value of the attributeList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attributeList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAttributeList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProductAttributeList }
     * 
     * 
     */
    public List<ProductAttributeList> getAttributeList() {
        if (attributeList == null) {
            attributeList = new ArrayList<ProductAttributeList>();
        }
        return this.attributeList;
    }

    /**
     * Gets the value of the localizedAttributeList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the localizedAttributeList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLocalizedAttributeList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProductLocalizedAttributeList }
     * 
     * 
     */
    public List<ProductLocalizedAttributeList> getLocalizedAttributeList() {
        if (localizedAttributeList == null) {
            localizedAttributeList = new ArrayList<ProductLocalizedAttributeList>();
        }
        return this.localizedAttributeList;
    }

}
