//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.30 at 06:38:40 PM PDT 
//


package com.hingeto.api;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RefundType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="RefundType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Returned"/>
 *     &lt;enumeration value="Missing"/>
 *     &lt;enumeration value="Refused"/>
 *     &lt;enumeration value="Resellable"/>
 *     &lt;enumeration value="NotSellable"/>
 *     &lt;enumeration value="Damaged"/>
 *     &lt;enumeration value="Defective"/>
 *     &lt;enumeration value="Other"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "RefundType")
@XmlEnum
public enum RefundType {

    @XmlEnumValue("Returned")
    RETURNED("Returned"),
    @XmlEnumValue("Missing")
    MISSING("Missing"),
    @XmlEnumValue("Refused")
    REFUSED("Refused"),
    @XmlEnumValue("Resellable")
    RESELLABLE("Resellable"),
    @XmlEnumValue("NotSellable")
    NOT_SELLABLE("NotSellable"),
    @XmlEnumValue("Damaged")
    DAMAGED("Damaged"),
    @XmlEnumValue("Defective")
    DEFECTIVE("Defective"),
    @XmlEnumValue("Other")
    OTHER("Other");
    private final String value;

    RefundType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static RefundType fromValue(String v) {
        for (RefundType c: RefundType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
