//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.30 at 06:38:40 PM PDT 
//


package com.hingeto.api;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RefundRejectionMessage complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RefundRejectionMessage">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Reason" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RefundAttributes" type="{https://www.hingeto.com/xml/V0.1}OrderAttributes" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RefundRejectionMessage", propOrder = {
    "reason",
    "refundAttributes"
})
public class RefundRejectionMessage {

    @XmlElement(name = "Reason", required = true)
    protected String reason;
    @XmlElement(name = "RefundAttributes")
    protected OrderAttributes refundAttributes;

    /**
     * Gets the value of the reason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReason() {
        return reason;
    }

    /**
     * Sets the value of the reason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReason(String value) {
        this.reason = value;
    }

    /**
     * Gets the value of the refundAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link OrderAttributes }
     *     
     */
    public OrderAttributes getRefundAttributes() {
        return refundAttributes;
    }

    /**
     * Sets the value of the refundAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderAttributes }
     *     
     */
    public void setRefundAttributes(OrderAttributes value) {
        this.refundAttributes = value;
    }

}
