//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.30 at 06:38:40 PM PDT 
//


package com.hingeto.api;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for RefundRequestMessage complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RefundRequestMessage">
 *   &lt;complexContent>
 *     &lt;extension base="{https://www.hingeto.com/xml/V0.1}Message">
 *       &lt;sequence>
 *         &lt;element name="RequestId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RefundDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="OrderID" type="{https://www.hingeto.com/xml/V0.1}OrderID"/>
 *         &lt;element name="OrderItemID" type="{https://www.hingeto.com/xml/V0.1}OrderItemCode"/>
 *         &lt;element name="Currency" type="{https://www.hingeto.com/xml/V0.1}CurrencyCode"/>
 *         &lt;element name="RefundAmount" type="{https://www.hingeto.com/xml/V0.1}BasePriceAmount"/>
 *         &lt;element name="RefundType" type="{https://www.hingeto.com/xml/V0.1}RefundType"/>
 *         &lt;element name="RefundRequestAttributes" type="{https://www.hingeto.com/xml/V0.1}OrderAttributes" minOccurs="0"/>
 *         &lt;element name="ListingID" type="{https://www.hingeto.com/xml/V0.1}ListingIDType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RefundRequestMessage", propOrder = {
    "requestId",
    "refundDate",
    "orderID",
    "orderItemID",
    "currency",
    "refundAmount",
    "refundType",
    "refundRequestAttributes",
    "listingID"
})
public class RefundRequestMessage
    extends Message
{

    @XmlElement(name = "RequestId", required = true)
    protected String requestId;
    @XmlElement(name = "RefundDate", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar refundDate;
    @XmlElement(name = "OrderID", required = true)
    protected String orderID;
    @XmlElement(name = "OrderItemID", required = true)
    protected String orderItemID;
    @XmlElement(name = "Currency", required = true)
    protected String currency;
    @XmlElement(name = "RefundAmount", required = true)
    protected BigDecimal refundAmount;
    @XmlElement(name = "RefundType", required = true)
    protected RefundType refundType;
    @XmlElement(name = "RefundRequestAttributes")
    protected OrderAttributes refundRequestAttributes;
    @XmlElement(name = "ListingID")
    protected ListingIDType listingID;

    /**
     * Gets the value of the requestId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestId() {
        return requestId;
    }

    /**
     * Sets the value of the requestId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestId(String value) {
        this.requestId = value;
    }

    /**
     * Gets the value of the refundDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRefundDate() {
        return refundDate;
    }

    /**
     * Sets the value of the refundDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRefundDate(XMLGregorianCalendar value) {
        this.refundDate = value;
    }

    /**
     * Gets the value of the orderID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderID() {
        return orderID;
    }

    /**
     * Sets the value of the orderID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderID(String value) {
        this.orderID = value;
    }

    /**
     * Gets the value of the orderItemID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderItemID() {
        return orderItemID;
    }

    /**
     * Sets the value of the orderItemID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderItemID(String value) {
        this.orderItemID = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrency(String value) {
        this.currency = value;
    }

    /**
     * Gets the value of the refundAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRefundAmount() {
        return refundAmount;
    }

    /**
     * Sets the value of the refundAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRefundAmount(BigDecimal value) {
        this.refundAmount = value;
    }

    /**
     * Gets the value of the refundType property.
     * 
     * @return
     *     possible object is
     *     {@link RefundType }
     *     
     */
    public RefundType getRefundType() {
        return refundType;
    }

    /**
     * Sets the value of the refundType property.
     * 
     * @param value
     *     allowed object is
     *     {@link RefundType }
     *     
     */
    public void setRefundType(RefundType value) {
        this.refundType = value;
    }

    /**
     * Gets the value of the refundRequestAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link OrderAttributes }
     *     
     */
    public OrderAttributes getRefundRequestAttributes() {
        return refundRequestAttributes;
    }

    /**
     * Sets the value of the refundRequestAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderAttributes }
     *     
     */
    public void setRefundRequestAttributes(OrderAttributes value) {
        this.refundRequestAttributes = value;
    }

    /**
     * Gets the value of the listingID property.
     * 
     * @return
     *     possible object is
     *     {@link ListingIDType }
     *     
     */
    public ListingIDType getListingID() {
        return listingID;
    }

    /**
     * Sets the value of the listingID property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListingIDType }
     *     
     */
    public void setListingID(ListingIDType value) {
        this.listingID = value;
    }

}
