//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.30 at 06:38:40 PM PDT 
//


package com.hingeto.api;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for SalesOrderMessage complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SalesOrderMessage">
 *   &lt;complexContent>
 *     &lt;extension base="{https://www.hingeto.com/xml/V0.1}Message">
 *       &lt;sequence>
 *         &lt;element name="OrderID" type="{https://www.hingeto.com/xml/V0.1}OrderID"/>
 *         &lt;element name="OrderDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="Currency" type="{https://www.hingeto.com/xml/V0.1}CurrencyCode"/>
 *         &lt;element name="BillingData" type="{https://www.hingeto.com/xml/V0.1}BillingData" minOccurs="0"/>
 *         &lt;element name="FulfillmentData" type="{https://www.hingeto.com/xml/V0.1}FulfillmentData"/>
 *         &lt;element name="OrderAttributes" type="{https://www.hingeto.com/xml/V0.1}OrderAttributes" minOccurs="0"/>
 *         &lt;element name="OrderItem" type="{https://www.hingeto.com/xml/V0.1}OrderItem" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SalesOrderMessage", propOrder = {
    "orderID",
    "orderDate",
    "currency",
    "billingData",
    "fulfillmentData",
    "orderAttributes",
    "orderItem"
})
public class SalesOrderMessage
    extends Message
{

    @XmlElement(name = "OrderID", required = true)
    protected String orderID;
    @XmlElement(name = "OrderDate", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar orderDate;
    @XmlElement(name = "Currency", required = true)
    protected String currency;
    @XmlElement(name = "BillingData")
    protected BillingData billingData;
    @XmlElement(name = "FulfillmentData", required = true)
    protected FulfillmentData fulfillmentData;
    @XmlElement(name = "OrderAttributes")
    protected OrderAttributes orderAttributes;
    @XmlElement(name = "OrderItem", required = true)
    protected List<OrderItem> orderItem;

    /**
     * Gets the value of the orderID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderID() {
        return orderID;
    }

    /**
     * Sets the value of the orderID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderID(String value) {
        this.orderID = value;
    }

    /**
     * Gets the value of the orderDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getOrderDate() {
        return orderDate;
    }

    /**
     * Sets the value of the orderDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setOrderDate(XMLGregorianCalendar value) {
        this.orderDate = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrency(String value) {
        this.currency = value;
    }

    /**
     * Gets the value of the billingData property.
     * 
     * @return
     *     possible object is
     *     {@link BillingData }
     *     
     */
    public BillingData getBillingData() {
        return billingData;
    }

    /**
     * Sets the value of the billingData property.
     * 
     * @param value
     *     allowed object is
     *     {@link BillingData }
     *     
     */
    public void setBillingData(BillingData value) {
        this.billingData = value;
    }

    /**
     * Gets the value of the fulfillmentData property.
     * 
     * @return
     *     possible object is
     *     {@link FulfillmentData }
     *     
     */
    public FulfillmentData getFulfillmentData() {
        return fulfillmentData;
    }

    /**
     * Sets the value of the fulfillmentData property.
     * 
     * @param value
     *     allowed object is
     *     {@link FulfillmentData }
     *     
     */
    public void setFulfillmentData(FulfillmentData value) {
        this.fulfillmentData = value;
    }

    /**
     * Gets the value of the orderAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link OrderAttributes }
     *     
     */
    public OrderAttributes getOrderAttributes() {
        return orderAttributes;
    }

    /**
     * Sets the value of the orderAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderAttributes }
     *     
     */
    public void setOrderAttributes(OrderAttributes value) {
        this.orderAttributes = value;
    }

    /**
     * Gets the value of the orderItem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the orderItem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrderItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OrderItem }
     * 
     * 
     */
    public List<OrderItem> getOrderItem() {
        if (orderItem == null) {
            orderItem = new ArrayList<OrderItem>();
        }
        return this.orderItem;
    }

}
