//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.30 at 06:38:40 PM PDT 
//


package com.hingeto.api;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ShippingCostModel.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ShippingCostModel">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Don't Calculate"/>
 *     &lt;enumeration value="Fixed"/>
 *     &lt;enumeration value="Weight"/>
 *     &lt;enumeration value="Price"/>
 *     &lt;enumeration value="Volume"/>
 *     &lt;enumeration value="BySupplier"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ShippingCostModel")
@XmlEnum
public enum ShippingCostModel {

    @XmlEnumValue("Don't Calculate")
    DON_T_CALCULATE("Don't Calculate"),
    @XmlEnumValue("Fixed")
    FIXED("Fixed"),
    @XmlEnumValue("Weight")
    WEIGHT("Weight"),
    @XmlEnumValue("Price")
    PRICE("Price"),
    @XmlEnumValue("Volume")
    VOLUME("Volume"),
    @XmlEnumValue("BySupplier")
    BY_SUPPLIER("BySupplier");
    private final String value;

    ShippingCostModel(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ShippingCostModel fromValue(String v) {
        for (ShippingCostModel c: ShippingCostModel.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
