//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.30 at 06:38:40 PM PDT 
//


package com.hingeto.api;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SupplierCommissionMessage complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SupplierCommissionMessage">
 *   &lt;complexContent>
 *     &lt;extension base="{https://www.hingeto.com/xml/V0.1}Message">
 *       &lt;sequence>
 *         &lt;element name="SupplierID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SupplierEffectiveID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SupplierName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DefaultCommission" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="FullRefreshFlag" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="CategoryCommission" type="{https://www.hingeto.com/xml/V0.1}CategoryCommissionType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SupplierCommissionMessage", propOrder = {
    "supplierID",
    "supplierEffectiveID",
    "supplierName",
    "defaultCommission",
    "fullRefreshFlag",
    "categoryCommission"
})
public class SupplierCommissionMessage
    extends Message
{

    @XmlElement(name = "SupplierID", required = true)
    protected String supplierID;
    @XmlElement(name = "SupplierEffectiveID", required = true)
    protected String supplierEffectiveID;
    @XmlElement(name = "SupplierName")
    protected String supplierName;
    @XmlElement(name = "DefaultCommission")
    protected BigDecimal defaultCommission;
    @XmlElement(name = "FullRefreshFlag", defaultValue = "true")
    protected boolean fullRefreshFlag;
    @XmlElement(name = "CategoryCommission")
    protected List<CategoryCommissionType> categoryCommission;

    /**
     * Gets the value of the supplierID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupplierID() {
        return supplierID;
    }

    /**
     * Sets the value of the supplierID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupplierID(String value) {
        this.supplierID = value;
    }

    /**
     * Gets the value of the supplierEffectiveID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupplierEffectiveID() {
        return supplierEffectiveID;
    }

    /**
     * Sets the value of the supplierEffectiveID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupplierEffectiveID(String value) {
        this.supplierEffectiveID = value;
    }

    /**
     * Gets the value of the supplierName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupplierName() {
        return supplierName;
    }

    /**
     * Sets the value of the supplierName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupplierName(String value) {
        this.supplierName = value;
    }

    /**
     * Gets the value of the defaultCommission property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDefaultCommission() {
        return defaultCommission;
    }

    /**
     * Sets the value of the defaultCommission property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDefaultCommission(BigDecimal value) {
        this.defaultCommission = value;
    }

    /**
     * Gets the value of the fullRefreshFlag property.
     * 
     */
    public boolean isFullRefreshFlag() {
        return fullRefreshFlag;
    }

    /**
     * Sets the value of the fullRefreshFlag property.
     * 
     */
    public void setFullRefreshFlag(boolean value) {
        this.fullRefreshFlag = value;
    }

    /**
     * Gets the value of the categoryCommission property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the categoryCommission property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCategoryCommission().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CategoryCommissionType }
     * 
     * 
     */
    public List<CategoryCommissionType> getCategoryCommission() {
        if (categoryCommission == null) {
            categoryCommission = new ArrayList<CategoryCommissionType>();
        }
        return this.categoryCommission;
    }

}
