//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.30 at 06:38:40 PM PDT 
//


package com.hingeto.api;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VariationChildren complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VariationChildren">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="VariationSKU" type="{https://www.hingeto.com/xml/V0.1}ProductSKU"/>
 *         &lt;element name="VariationStorefrontProductID" type="{https://www.hingeto.com/xml/V0.1}StorefrontProductIDType" minOccurs="0"/>
 *         &lt;element name="VariationContent" type="{https://www.hingeto.com/xml/V0.1}ProductContentType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VariationChildren", propOrder = {
    "variationSKU",
    "variationStorefrontProductID",
    "variationContent"
})
public class VariationChildren {

    @XmlElement(name = "VariationSKU", required = true)
    protected String variationSKU;
    @XmlElement(name = "VariationStorefrontProductID")
    protected String variationStorefrontProductID;
    @XmlElement(name = "VariationContent")
    protected ProductContentType variationContent;

    /**
     * Gets the value of the variationSKU property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVariationSKU() {
        return variationSKU;
    }

    /**
     * Sets the value of the variationSKU property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVariationSKU(String value) {
        this.variationSKU = value;
    }

    /**
     * Gets the value of the variationStorefrontProductID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVariationStorefrontProductID() {
        return variationStorefrontProductID;
    }

    /**
     * Sets the value of the variationStorefrontProductID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVariationStorefrontProductID(String value) {
        this.variationStorefrontProductID = value;
    }

    /**
     * Gets the value of the variationContent property.
     * 
     * @return
     *     possible object is
     *     {@link ProductContentType }
     *     
     */
    public ProductContentType getVariationContent() {
        return variationContent;
    }

    /**
     * Sets the value of the variationContent property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductContentType }
     *     
     */
    public void setVariationContent(ProductContentType value) {
        this.variationContent = value;
    }

}
